// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.7.0 (commit 02c67d121b0d08478eaf3512f479e7a326d39940).

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

// Import and reexport all reducer arg types
import { CreateOrUpdateSigner } from "./create_or_update_signer_reducer.ts";
export { CreateOrUpdateSigner };
import { GetUserSigner } from "./get_user_signer_reducer.ts";
export { GetUserSigner };

// Import and reexport all table handle types
import { UserSignerTableHandle } from "./user_signer_table.ts";
export { UserSignerTableHandle };

// Import and reexport all types
import { UserSigner } from "./user_signer_type.ts";
export { UserSigner };

const REMOTE_MODULE = {
  tables: {
    user_signer: {
      tableName: "user_signer" as const,
      rowType: UserSigner.getTypeScriptAlgebraicType(),
      primaryKey: "signerUuid",
      primaryKeyInfo: {
        colName: "signerUuid",
        colType: (UserSigner.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    create_or_update_signer: {
      reducerName: "create_or_update_signer",
      argsType: CreateOrUpdateSigner.getTypeScriptAlgebraicType(),
    },
    get_user_signer: {
      reducerName: "get_user_signer",
      argsType: GetUserSigner.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.7.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: __DbConnectionImpl, event: __Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: __DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: __DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "CreateOrUpdateSigner", args: CreateOrUpdateSigner }
| { name: "GetUserSigner", args: GetUserSigner }
;

export class RemoteReducers {
  constructor(private connection: __DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  createOrUpdateSigner(userFid: bigint, signerUuid: string, publicKey: string, status: string, createdAt: bigint) {
    const __args = { userFid, signerUuid, publicKey, status, createdAt };
    let __writer = new __BinaryWriter(1024);
    CreateOrUpdateSigner.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_or_update_signer", __argsBuffer, this.setCallReducerFlags.createOrUpdateSignerFlags);
  }

  onCreateOrUpdateSigner(callback: (ctx: ReducerEventContext, userFid: bigint, signerUuid: string, publicKey: string, status: string, createdAt: bigint) => void) {
    this.connection.onReducer("create_or_update_signer", callback);
  }

  removeOnCreateOrUpdateSigner(callback: (ctx: ReducerEventContext, userFid: bigint, signerUuid: string, publicKey: string, status: string, createdAt: bigint) => void) {
    this.connection.offReducer("create_or_update_signer", callback);
  }

  getUserSigner(userFid: bigint) {
    const __args = { userFid };
    let __writer = new __BinaryWriter(1024);
    GetUserSigner.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("get_user_signer", __argsBuffer, this.setCallReducerFlags.getUserSignerFlags);
  }

  onGetUserSigner(callback: (ctx: ReducerEventContext, userFid: bigint) => void) {
    this.connection.onReducer("get_user_signer", callback);
  }

  removeOnGetUserSigner(callback: (ctx: ReducerEventContext, userFid: bigint) => void) {
    this.connection.offReducer("get_user_signer", callback);
  }

}

export class SetReducerFlags {
  createOrUpdateSignerFlags: __CallReducerFlags = 'FullUpdate';
  createOrUpdateSigner(flags: __CallReducerFlags) {
    this.createOrUpdateSignerFlags = flags;
  }

  getUserSignerFlags: __CallReducerFlags = 'FullUpdate';
  getUserSigner(flags: __CallReducerFlags) {
    this.getUserSignerFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: __DbConnectionImpl) {}

  get userSigner(): UserSignerTableHandle<'user_signer'> {
    // clientCache is a private property
    return new UserSignerTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<UserSigner>(REMOTE_MODULE.tables.user_signer));
  }
}

export class SubscriptionBuilder extends __SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends __DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: __DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = __EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = __ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = __SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = __ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
