// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

export type UserSigner = {
  signerUuid: string,
  userFid: bigint,
  publicKey: string,
  status: string,
  createdAt: bigint,
};
let _cached_UserSigner_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const UserSigner = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_UserSigner_type_value) return _cached_UserSigner_type_value;
    _cached_UserSigner_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_UserSigner_type_value.value.elements.push(
      { name: "signerUuid", algebraicType: __AlgebraicTypeValue.String },
      { name: "userFid", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "publicKey", algebraicType: __AlgebraicTypeValue.String },
      { name: "status", algebraicType: __AlgebraicTypeValue.String },
      { name: "createdAt", algebraicType: __AlgebraicTypeValue.U64 },
    );
    return _cached_UserSigner_type_value;
  },

  serialize(writer: __BinaryWriter, value: UserSigner): void {
    __AlgebraicTypeValue.serializeValue(writer, UserSigner.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): UserSigner {
    return __AlgebraicTypeValue.deserializeValue(reader, UserSigner.getTypeScriptAlgebraicType());
  },

}

export default UserSigner;


